In [77]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import json

In [78]:
# Read csv file into pandas dataframe
transactions = pd.read_excel('FoodUtilitiesGroceriesGas.xlsx')
transactions

Day  Month  Year  Amount  Five Guys  In N Out  Chick-Fil-A  \
0      4      9  2021  -63.77          0         0            0   
1      3      9  2021  -22.76          0         0            1   
2      3      9  2021  -17.12          0         0            0   
3      3      9  2021 -124.07          0         0            0   
4      2      9  2021  -16.51          0         0            0   
5      2      9  2021  -38.67          0         0            0   
6      1      9  2021   -9.72          0         0            0   
7      1      9  2021  -23.73          0         0            0   
8     31      8  2021  -31.58          0         0            0   
9     31      8  2021 -212.73          0         0            0   
10    31      8  2021  -71.00          0         0            1   
11    30      8  2021  -43.87          0         0            0   
12    30      8  2021  -12.64          0         0            0   
13    30      8  2021  -25.19          1         0            0   
14    30      8  2021  -93.16          0         0            0   
15    30      8  2021  -30.50          0         0            0   
16    30      8  2021  -61.32          0         0            0   
17    28      8  2021  -86.71          1         0            0   
18    27      8  2021 -103.51          0         0            0   
19    27      8  2021  -37.00          0         0            0   
20    26      8  2021  -30.00          0         0            0   
21    24      8  2021 -174.66          0         0            0   
22    23      8  2021  -47.59          0         0            0   
23    23      8  2021  -33.51          1         0            0   
24    21      8  2021 -169.44          0         0            0   
25    17      8  2021 -132.00          0         0            0   
26    17      8  2021 -388.98          0         0            0   
27    16      8  2021 -104.85          0         0            0   
28    16      8  2021 -315.18          0         0            0   
29    14      8  2021  -58.78          0         0            0   
30    14      8  2021  -12.11          0         0            1   
31    14      8  2021   -7.57          0         0            0   
32    13      8  2021   -6.52          0         0            0   
33    13      8  2021 -162.00          0         0            0   
34    12      8  2021  -20.33          0         0            0   
35    12      8  2021   -4.87          0         0            1   
36    11      8  2021   -9.35          0         0            0   
37    10      8  2021  -24.13          0         0            0   
38     9      8  2021  -15.31          0         0            0   
39     9      8  2021  -10.61          0         0            0   
40     6      8  2021 -880.24          0         0            0   
41     6      8  2021  -25.00          0         0            0   
42     6      8  2021   -9.74          0         0            1   
43     5      8  2021  -58.50          0         0            0   
44     2      8  2021  -85.23          0         0            0   
45     2      8  2021  -37.35          0         0            0   
46     2      8  2021  -47.81          0         0            0   
47    26      7  2021  -22.85          0         0            0   
48    26      7  2021  -47.66          0         0            0   
49    22      7  2021 -174.66          0         0            0   
50    21      7  2021  -81.25          0         0            0   
51    21      7  2021   -8.94          0         0            0   
52    20      7  2021  -61.53          0         0            0   
53    19      7  2021  -14.05          0         0            0   
54    19      7  2021  -67.86          0         0            0   
55    19      7  2021  -53.79          0         0            0   
56    19      7  2021  -14.18          0         0            0   
57    19      7  2021   -9.89          1         0            0   
58    17      7  2021  -30.00          0         0  

In [79]:
from dataFrameBuilder import buildDataFrame
# pd.set_option("display.max_rows", None, "display.max_columns", None)

df = buildDataFrame()
df = df.drop('Merchant Name', axis=1)
df

2021-11-06 5.4 Uber 063015 SF**POOL**
2021-11-04 78.5 Touchstone Climbing
2021-11-04 -500 United Airlines
2021-11-03 12 McDonald's
2021-11-03 4.33 Starbucks
2021-11-02 89.4 SparkFun
2021-10-22 500 United Airlines
2021-10-20 6.33 Uber 072515 SF**POOL**
2021-10-17 500 Tectra Inc
2021-10-16 500 KFC
2021-10-16 500 Madison Bicycle Shop
2021-10-07 5.4 Uber 063015 SF**POOL**
2021-10-05 78.5 Touchstone Climbing
2021-10-05 -500 United Airlines
2021-10-04 12 McDonald's
2021-10-04 4.33 Starbucks
2021-10-03 89.4 SparkFun
2021-09-22 500 United Airlines
2021-09-20 6.33 Uber 072515 SF**POOL**
2021-09-17 500 Tectra Inc
2021-09-16 500 KFC
2021-09-16 500 Madison Bicycle Shop
2021-09-07 5.4 Uber 063015 SF**POOL**
2021-09-05 78.5 Touchstone Climbing
2021-09-05 -500 United Airlines
2021-09-04 12 McDonald's
2021-09-04 4.33 Starbucks
2021-09-03 89.4 SparkFun
2021-08-23 500 United Airlines
2021-08-21 6.33 Uber 072515 SF**POOL**
2021-08-18 500 Tectra Inc
2021-08-17 500 KFC
2021-08-17 500 Madison Bicycle Shop
2

Day Month  Year  Amount  Uber  Touchstone  United Airlines  McDonald's  \
0     6    11  2021    5.40     1           0                0           0   
1     4    11  2021   78.50     0           1                0           0   
2     4    11  2021 -500.00     0           0                1           0   
3     3    11  2021   12.00     0           0                0           1   
4     3    11  2021    4.33     0           0                0           0   
5     2    11  2021   89.40     0           0                0           0   
6    22    10  2021  500.00     0           0                1           0   
7    20    10  2021    6.33     1           0                0           0   
8    17    10  2021  500.00     0           0                0           0   
9    16    10  2021  500.00     0           0                0           0   
10   16    10  2021  500.00     0           0                0           0   
11    7    10  2021    5.40     1           0                0           0   
12    5    10  2021   78.50     0           1                0           0   
13    5    10  2021 -500.00     0           0                1           0   
14    4    10  2021   12.00     0           0                0           1   
15    4    10  2021    4.33     0           0                0           0   
16    3    10  2021   89.40     0           0                0           0   
17   22     9  2021  500.00     0           0                1           0   
18   20     9  2021    6.33     1           0                0           0   
19   17     9  2021  500.00     0           0                0           0   
20   16     9  2021  500.00     0           0                0           0   
21   16     9  2021  500.00     0           0                0           0   
22    7     9  2021    5.40     1           0                0           0   
23    5     9  2021   78.50     0           1                0           0   
24    5     9  2021 -500.00     0           0                1           0   
25    4     9  2021   12.00     0           0                0           1   
26    4     9  2021    4.33     0           0                0           0   
27    3     9  2021   89.40     0           0                0           0   
28   23     8  2021  500.00     0           0                1           0   
29   21     8  2021    6.33     1           0                0           0   
30   18     8  2021  500.00     0           0                0           0   
31   17     8  2021  500.00     0           0                0           0   
32   17     8  2021  500.00     0           0                0           0   
33    8     8  2021    5.40     1           0                0           0   
34    6     8  2021   78.50     0           1                0           0   
35    6     8  2021 -500.00     0           0                1           0   
36    5     8  2021   12.00     0           0                0           1   
37    5     8  2021    4.33     0           0                0           0   
38    4     8  2021   89.40     0           0                0           0   
39   24     7  2021  500.00     0           0                1           0   
40   22     7  2021    6.33     1           0                0           0   
41   19     7  2021  500.00     0           0                0           0   
42   18     7  2021  500.00     0           0                0           0   
43   18     7  2021  500.00     0           0                0           0   
44    9     7  2021    5.40     1           0                0           0   
45    7     7  2021   78.50     0           1                0           0   
46    7     7  2021 -500.00     0           0                1           0   
47    6     7  2021   12.00     0           0                0           1   
48    6     7  2021    4.33     0           0                0           0   
49    5     7  2021   89.40     0           0                0           0   
50   24     6  2021  500.0

In [80]:
transactions.describe().transpose()

count         mean         std      min     25%  \
Day                   592.0    16.021959    8.435353     1.00     9.0   
Month                 592.0     5.746622    3.130007     1.00     3.0   
Year                  592.0  2020.525338    0.551294  2019.00  2020.0   
Amount                592.0   -73.716503  115.621845  -909.83   -85.6   
Five Guys             592.0     0.043919    0.205088     0.00     0.0   
In N Out              592.0     0.015203    0.122462     0.00     0.0   
Chick-Fil-A           592.0     0.047297    0.212454     0.00     0.0   
Little Caesars        592.0     0.033784    0.180825     0.00     0.0   
Cafe Rio              592.0     0.013514    0.115557     0.00     0.0   
Taco Bell             592.0     0.028716    0.167149     0.00     0.0   
Chipotle              592.0     0.010135    0.100247     0.00     0.0   
Wendys                592.0     0.023649    0.152080     0.00     0.0   
Arbys                 592.0     0.025338    0.157282     0.00     0.0   
Burger King           592.0     0.011824    0.108186     0.00     0.0   
McDonalds             592.0     0.020270    0.141043     0.00     0.0   
Arctic Circle         592.0     0.003378    0.058075     0.00     0.0   
Sonic                 592.0     0.001689    0.041100     0.00     0.0   
Rancheritos           592.0     0.005068    0.071066     0.00     0.0   
Mesq Mex Grill        592.0     0.001689    0.041100     0.00     0.0   
Flying Pie Pizzeria   592.0     0.001689    0.041100     0.00     0.0   
Jimmy Johns           592.0     0.003378    0.058075     0.00     0.0   
Freebirds             592.0     0.008446    0.091590     0.00     0.0   
Panda Exp             592.0     0.001689    0.041100     0.00     0.0   
Moochies              592.0     0.001689    0.041100     0.00     0.0   
Pizza Hut             592.0     0.001689    0.041100     0.00     0.0   
Cal Mex Food          592.0     0.001689    0.041100     0.00     0.0   
Kneaders              592.0     0.001689    0.041100     0.00     0.0   
Jamba                 592.0     0.001689    0.041100     0.00     0.0   
U Vending Machine     592.0     0.001689    0.041100     0.00     0.0   
Crumbl                592.0     0.010135    0.100247     0.00     0.0   
Rocky Mountain Power  592.0     0.025338    0.157282     0.00     0.0   
QuestarGas            592.0     0.021959    0.146675     0.00     0.0   
GrangerHunter         592.0     0.025338    0.157282     0.00     0.0   
WVCC                  592.0     0.027027    0.162299     0.00     0.0   
Utah Infras           592.0     0.025338    0.157282     0.00     0.0   
Xmission              592.0     0.025338    0.157282     0.00     0.0   
Walgreens             592.0     0.001689    0.041100     0.00     0.0   
Winco                 592.0     0.035473    0.185128     0.00     0.0   
Walmart               592.0     0.028716    0.167149     0.00     0.0   
Lucky                 592.0     0.008446    0.091590     0.00     0.0   
Sams Club             592.0     0.030405    0.171845     0.00     0.0   
Maceys                592.0     0.005068    0.071066     0.00     0.0   
Davis                 592.0     0.023649    0.152080     0.00     0.0   
Harmons               592.0     0.008446    0.091590     0.00     0.0   
Reams                 592.0     0.005068    0.071066     0.00     0.0   
Smiths                592.0     0.018581    0.135154     0.00     0.0   
Albertsons            592.0     0.001689    0.041100     0.00     0.0   
Fresh Market          592.0     0.001689    0.041100     0.00     0.0   
NPS                   592.0     0.001689    0.041100     0.00     0.0   
Earthgrains           592.0     0.003378    0.058075     0.00     0.0   
Chevron               592.0     0.072635    0.259756     0.00     0.0   
Shell                 592.0     0.013514    0.115557     0.00     0.0   
Costco Gas            592.0     0.018581    0.135154     0.00     0.0   
Maverik               592.0     0.010135    0.100247     0.00     0.0   
7-Eleve

In [81]:
transactions = df

In [82]:
X = transactions.drop('Categories', axis=1)
y = transactions['Categories']

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
print(len(X_train), len(X_test))


196 66


In [84]:
scaler = StandardScaler()

In [85]:
# Fit only to the training data
scaler.fit(X_train)

StandardScaler()

In [86]:
StandardScaler(copy=True, with_mean=True, with_std=True)

StandardScaler()

In [87]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [88]:
mlp = MLPClassifier(hidden_layer_sizes=(60,90,120,90,60),max_iter=100000)

In [89]:
mlp.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(60, 90, 120, 90, 60), max_iter=100000)

In [90]:
predictions = mlp.predict(X_test)

In [91]:
print(confusion_matrix(y_test, predictions))

[[11  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0]
 [ 0  0  0  9  0  0  0  0]
 [ 0  0  0  0  6  0  0  0]
 [ 0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  8  0]
 [ 0  0  0  0  0  0  0  4]]


In [92]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         9
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00         9
           5       1.00      1.00      1.00         6
           6       1.00      1.00      1.00         8
           7       1.00      1.00      1.00         8
           8       1.00      1.00      1.00         4

    accuracy                           1.00        66
   macro avg       1.00      1.00      1.00        66
weighted avg       1.00      1.00      1.00        66



In [106]:
# Read excel file into pandas dataframe
small_batch = pd.read_excel('small_batch.xlsx')
small_batch = transactions
small_batch

Day Month  Year  Amount  Uber  Touchstone  United Airlines  McDonald's  \
0     6    11  2021    5.40     1           0                0           0   
1     4    11  2021   78.50     0           1                0           0   
2     4    11  2021 -500.00     0           0                1           0   
3     3    11  2021   12.00     0           0                0           1   
4     3    11  2021    4.33     0           0                0           0   
5     2    11  2021   89.40     0           0                0           0   
6    22    10  2021  500.00     0           0                1           0   
7    20    10  2021    6.33     1           0                0           0   
8    17    10  2021  500.00     0           0                0           0   
9    16    10  2021  500.00     0           0                0           0   
10   16    10  2021  500.00     0           0                0           0   
11    7    10  2021    5.40     1           0                0           0   
12    5    10  2021   78.50     0           1                0           0   
13    5    10  2021 -500.00     0           0                1           0   
14    4    10  2021   12.00     0           0                0           1   
15    4    10  2021    4.33     0           0                0           0   
16    3    10  2021   89.40     0           0                0           0   
17   22     9  2021  500.00     0           0                1           0   
18   20     9  2021    6.33     1           0                0           0   
19   17     9  2021  500.00     0           0                0           0   
20   16     9  2021  500.00     0           0                0           0   
21   16     9  2021  500.00     0           0                0           0   
22    7     9  2021    5.40     1           0                0           0   
23    5     9  2021   78.50     0           1                0           0   
24    5     9  2021 -500.00     0           0                1           0   
25    4     9  2021   12.00     0           0                0           1   
26    4     9  2021    4.33     0           0                0           0   
27    3     9  2021   89.40     0           0                0           0   
28   23     8  2021  500.00     0           0                1           0   
29   21     8  2021    6.33     1           0                0           0   
30   18     8  2021  500.00     0           0                0           0   
31   17     8  2021  500.00     0           0                0           0   
32   17     8  2021  500.00     0           0                0           0   
33    8     8  2021    5.40     1           0                0           0   
34    6     8  2021   78.50     0           1                0           0   
35    6     8  2021 -500.00     0           0                1           0   
36    5     8  2021   12.00     0           0                0           1   
37    5     8  2021    4.33     0           0                0           0   
38    4     8  2021   89.40     0           0                0           0   
39   24     7  2021  500.00     0           0                1           0   
40   22     7  2021    6.33     1           0                0           0   
41   19     7  2021  500.00     0           0                0           0   
42   18     7  2021  500.00     0           0                0           0   
43   18     7  2021  500.00     0           0                0           0   
44    9     7  2021    5.40     1           0                0           0   
45    7     7  2021   78.50     0           1                0           0   
46    7     7  2021 -500.00     0           0                1           0   
47    6     7  2021   12.00     0           0                0           1   
48    6     7  2021    4.33     0           0                0           0   
49    5     7  2021   89.40     0           0                0           0   
50   24     6  2021  500.0

In [107]:
# Separate Label from transaction
X = small_batch.drop('Categories', axis=1)
y = small_batch['Categories']

In [108]:
# Scale the data
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X)
StandardScaler(copy=True, with_mean=True, with_std=True)
# Now apply the transformations to the data:
X = scaler.transform(X)

In [109]:
predictions = mlp.predict(X)
predictions

array([1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8,
       1, 2, 3, 4, 5, 6, 3, 1, 7, 4, 8, 1, 2, 3, 4, 5, 6, 3, 1, 7])

In [110]:
print(confusion_matrix(y, predictions))

[[48  0  0  0  0  0  0  0]
 [ 0 24  0  0  0  0  0  0]
 [ 0  0 48  0  0  0  0  0]
 [ 0  0  0 47  0  0  0  0]
 [ 0  0  0  0 24  0  0  0]
 [ 0  0  0  0  0 24  0  0]
 [ 0  0  0  0  0  0 24  0]
 [ 0  0  0  0  0  0  0 23]]


In [111]:
for (predict, actual, score) in zip(predictions, y, mlp.predict_proba(X)):
    print("prediction: ", predict, "actual: ", actual, "confidence: ", score)

prediction:  1 actual:  1 confidence:  [9.99235247e-01 4.96264715e-04 5.64757696e-05 5.68193402e-07
 5.80456675e-05 3.28343782e-06 1.41805237e-04 8.31013198e-06]
prediction:  2 actual:  2 confidence:  [1.76466311e-04 9.98272532e-01 3.67928921e-07 7.66317446e-05
 3.41934611e-04 3.22986681e-04 4.16477372e-06 8.04915636e-04]
prediction:  3 actual:  3 confidence:  [2.02743174e-06 4.41766531e-07 9.99936578e-01 7.62876646e-07
 3.67783602e-05 1.96725473e-06 1.92227430e-05 2.22179803e-06]
prediction:  4 actual:  4 confidence:  [2.98900575e-10 3.38395626e-07 2.44687368e-07 9.99883926e-01
 1.95571827e-05 1.76536214e-05 1.30204313e-07 7.81491378e-05]
prediction:  5 actual:  5 confidence:  [3.98146054e-06 1.08948871e-05 4.48727676e-05 1.85011594e-05
 9.99773555e-01 9.07624141e-05 9.07459610e-07 5.65248615e-05]
prediction:  6 actual:  6 confidence:  [3.42859095e-08 1.03400817e-05 9.32621308e-07 3.46721448e-05
 3.28606901e-04 9.99575816e-01 2.39241911e-08 4.95739619e-05]
prediction:  3 actual:  3 co

In [112]:
for (i, predict, actual, score) in zip(y.index, predictions, y, mlp.predict_proba(X)):
    print("DataPoint: ", i, "prediction: ", predict, "actual: ", actual, "confidence: ", score)

array = mlp.predict_proba(X).tolist()


def topThreeIndices(array):
    topThree = []
    second_array = []
    # Make deep copy of array
    for i in range(len(array)):
        second_array.append(0)
        second_array[i] = array[i]
    for i in range(3):
        max_value = max(second_array)
        max_index = array.index(max_value)
        topThree.append(max_index)
        second_array.remove(max_value)
    return topThree

results = []
for predictions in array:
    result = topThreeIndices(predictions)
    results.append(result)

with open('NeuralNetworkPredictions.json', 'w') as jsonfile:
    json_results = {}
    json_results["Predictions"] = results
    json.dump(json_results, jsonfile)


DataPoint:  0 prediction:  1 actual:  1 confidence:  [9.99235247e-01 4.96264715e-04 5.64757696e-05 5.68193402e-07
 5.80456675e-05 3.28343782e-06 1.41805237e-04 8.31013198e-06]
DataPoint:  1 prediction:  2 actual:  2 confidence:  [1.76466311e-04 9.98272532e-01 3.67928921e-07 7.66317446e-05
 3.41934611e-04 3.22986681e-04 4.16477372e-06 8.04915636e-04]
DataPoint:  2 prediction:  3 actual:  3 confidence:  [2.02743174e-06 4.41766531e-07 9.99936578e-01 7.62876646e-07
 3.67783602e-05 1.96725473e-06 1.92227430e-05 2.22179803e-06]
DataPoint:  3 prediction:  4 actual:  4 confidence:  [2.98900575e-10 3.38395626e-07 2.44687368e-07 9.99883926e-01
 1.95571827e-05 1.76536214e-05 1.30204313e-07 7.81491378e-05]
DataPoint:  4 prediction:  5 actual:  5 confidence:  [3.98146054e-06 1.08948871e-05 4.48727676e-05 1.85011594e-05
 9.99773555e-01 9.07624141e-05 9.07459610e-07 5.65248615e-05]
DataPoint:  5 prediction:  6 actual:  6 confidence:  [3.42859095e-08 1.03400817e-05 9.32621308e-07 3.46721448e-05
 3.286