In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import json

In [2]:
# Read csv file into pandas dataframe
transactions = pd.read_excel('FoodUtilitiesGroceriesGas.xlsx')

In [3]:
from dataFrameBuilder import buildDataFrame
pd.set_option("display.max_rows", None, "display.max_columns", None)

# buildDataFrame() is reading data from file
df = buildDataFrame()
df = df.drop('Merchant Name', axis=1)
df

2021-09-09 880.24 ACH Withdrawal US BANK HOME MTG 0 - MTGPYMENT
2021-09-08 3.43 Chevron
2021-09-07 100 Kohl's
2021-09-07 20 PoS Withdrawal 1021572 ANYTHING FOR A FRIEND
2021-09-07 17.93 PoS Withdrawal ARBYS #155 WEST 4663 S 2700 W
2021-09-07 30.76 PoS Withdrawal CRUMBL
2021-09-07 46.6 Walmart
2021-09-07 72.47 Walmart
2021-09-04 51.79 Amazon
2021-09-04 19.61 CVS
2021-09-04 109.03 Home Depot
2021-09-04 293 PoS Withdrawal 844028311885 AT&T MOBILITY EPAY
2021-09-04 63.77 PoS Withdrawal HOLIDAY OIL #17 3210 W 3500 S SALT LAKE CITUTUS
2021-09-03 22.76 Chick-fil-A
2021-09-03 17.12 Sam's Club
2021-09-03 124.07 Sam's Club
2021-09-02 267 PoS Withdrawal 24266100005336 ABS TOWING & STORAGSpanish Fork
2021-09-02 16.51 PoS Withdrawal 650000007710414 MESQUITE MEXICAN GRILL SALT LAKE CITUTUS
2021-09-02 38.67 PoS Withdrawal ARBYS #155 WEST 4663 S 2700 W
2021-09-01 240.76 PoS Withdrawal 395708457148 MK Cosmetic
2021-09-01 23.73 PoS Withdrawal 4445000679803 LITTLE CAESARS 011
2021-09-01 9.72 Wendy's
2021

Day Month  Year  Amount  Home Mtg  Chevron  Kohl's  Anything For A Friend  \
0     9     9  2021  880.24         1        0       0                      0   
1     8     9  2021    3.43         0        1       0                      0   
2     7     9  2021  100.00         0        0       1                      0   
3     7     9  2021   20.00         0        0       0                      1   
4     7     9  2021   17.93         0        0       0                      0   
5     7     9  2021   30.76         0        0       0                      0   
6     7     9  2021   46.60         0        0       0                      0   
7     7     9  2021   72.47         0        0       0                      0   
8     4     9  2021   51.79         0        0       0                      0   
9     4     9  2021   19.61         0        0       0                      0   
10    4     9  2021  109.03         0        0       0                      0   
11    4     9  2021  293.00         0        0       0                      0   
12    4     9  2021   63.77         0        0       0                      0   
13    3     9  2021   22.76         0        0       0                      0   
14    3     9  2021   17.12         0        0       0                      0   
15    3     9  2021  124.07         0        0       0                      0   
16    2     9  2021  267.00         0        0       0                      0   
17    2     9  2021   16.51         0        0       0                      0   
18    2     9  2021   38.67         0        0       0                      0   
19    1     9  2021  240.76         0        0       0                      0   
20    1     9  2021   23.73         0        0       0                      0   
21    1     9  2021    9.72         0        0       0                      0   
22   31     8  2021   71.00         0        0       0                      0   
23   31     8  2021    4.29         0        0       0                      0   
24   31     8  2021   22.00         0        0       0                      0   
25   31     8  2021  153.36         0        0       0                      0   
26   31     8  2021   75.06         0        0       0                      0   
27   30     8  2021   61.32         0        0       0                      0   
28   30     8  2021   43.87         0        1       0                      0   
29   30     8  2021   25.19         0        0       0                      0   
30   30     8  2021    4.28         0        0       0                      0   
31   30     8  2021   12.64         0        0       0                      0   
32   30     8  2021   30.50         0        0       0                      0   
33   28     8  2021   86.71         0        0       0                      0   
34   27     8  2021   76.28         0        0       0                      0   
35   27     8  2021   37.00         0        0       0                      0   
36   27     8  2021  103.51         0        0       0                      0   
37   26     8  2021   58.10         0        0       0                      0   
38   26     8  2021   30.00         0        0       0                      0   
39   26     8  2021   32.34         0        0       0                      0   
40   26     8  2021   28.95         0        0       0                      0   
41   24     8  2021  174.66         0        0       0                      0   
42   23     8  2021   33.51         0        0       0                      0   
43   23     8  2021    0.99         0        0       0                      0   
44   23     8  2021   47.59         0        0       0                      0   
45   21     8  2021  169.44         0        0       0                      0   
46   20     8  2021    3.43         0        1       0                      0   
47   18     8  2021    9.61         0        1       0                      0   
48   18     8  2021   12.01        

In [4]:
transactions.describe().transpose()

count         mean         std      min     25%  \
Day                   592.0    16.021959    8.435353     1.00     9.0   
Month                 592.0     5.746622    3.130007     1.00     3.0   
Year                  592.0  2020.525338    0.551294  2019.00  2020.0   
Amount                592.0   -73.716503  115.621845  -909.83   -85.6   
Five Guys             592.0     0.043919    0.205088     0.00     0.0   
In N Out              592.0     0.015203    0.122462     0.00     0.0   
Chick-Fil-A           592.0     0.047297    0.212454     0.00     0.0   
Little Caesars        592.0     0.033784    0.180825     0.00     0.0   
Cafe Rio              592.0     0.013514    0.115557     0.00     0.0   
Taco Bell             592.0     0.028716    0.167149     0.00     0.0   
Chipotle              592.0     0.010135    0.100247     0.00     0.0   
Wendys                592.0     0.023649    0.152080     0.00     0.0   
Arbys                 592.0     0.025338    0.157282     0.00     0.0   
Burger King           592.0     0.011824    0.108186     0.00     0.0   
McDonalds             592.0     0.020270    0.141043     0.00     0.0   
Arctic Circle         592.0     0.003378    0.058075     0.00     0.0   
Sonic                 592.0     0.001689    0.041100     0.00     0.0   
Rancheritos           592.0     0.005068    0.071066     0.00     0.0   
Mesq Mex Grill        592.0     0.001689    0.041100     0.00     0.0   
Flying Pie Pizzeria   592.0     0.001689    0.041100     0.00     0.0   
Jimmy Johns           592.0     0.003378    0.058075     0.00     0.0   
Freebirds             592.0     0.008446    0.091590     0.00     0.0   
Panda Exp             592.0     0.001689    0.041100     0.00     0.0   
Moochies              592.0     0.001689    0.041100     0.00     0.0   
Pizza Hut             592.0     0.001689    0.041100     0.00     0.0   
Cal Mex Food          592.0     0.001689    0.041100     0.00     0.0   
Kneaders              592.0     0.001689    0.041100     0.00     0.0   
Jamba                 592.0     0.001689    0.041100     0.00     0.0   
U Vending Machine     592.0     0.001689    0.041100     0.00     0.0   
Crumbl                592.0     0.010135    0.100247     0.00     0.0   
Rocky Mountain Power  592.0     0.025338    0.157282     0.00     0.0   
QuestarGas            592.0     0.021959    0.146675     0.00     0.0   
GrangerHunter         592.0     0.025338    0.157282     0.00     0.0   
WVCC                  592.0     0.027027    0.162299     0.00     0.0   
Utah Infras           592.0     0.025338    0.157282     0.00     0.0   
Xmission              592.0     0.025338    0.157282     0.00     0.0   
Walgreens             592.0     0.001689    0.041100     0.00     0.0   
Winco                 592.0     0.035473    0.185128     0.00     0.0   
Walmart               592.0     0.028716    0.167149     0.00     0.0   
Lucky                 592.0     0.008446    0.091590     0.00     0.0   
Sams Club             592.0     0.030405    0.171845     0.00     0.0   
Maceys                592.0     0.005068    0.071066     0.00     0.0   
Davis                 592.0     0.023649    0.152080     0.00     0.0   
Harmons               592.0     0.008446    0.091590     0.00     0.0   
Reams                 592.0     0.005068    0.071066     0.00     0.0   
Smiths                592.0     0.018581    0.135154     0.00     0.0   
Albertsons            592.0     0.001689    0.041100     0.00     0.0   
Fresh Market          592.0     0.001689    0.041100     0.00     0.0   
NPS                   592.0     0.001689    0.041100     0.00     0.0   
Earthgrains           592.0     0.003378    0.058075     0.00     0.0   
Chevron               592.0     0.072635    0.259756     0.00     0.0   
Shell                 592.0     0.013514    0.115557     0.00     0.0   
Costco Gas            592.0     0.018581    0.135154     0.00     0.0   
Maverik               592.0     0.010135    0.100247     0.00     0.0   
7-Eleve

In [5]:
transactions = df

In [6]:
X = transactions.drop('Categories', axis=1)
y = transactions['Categories']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
print(len(X_train), len(X_test))


230 77


In [8]:
scaler = StandardScaler()

In [9]:
# Fit only to the training data
scaler.fit(X_train)

StandardScaler()

In [10]:
StandardScaler(copy=True, with_mean=True, with_std=True)

StandardScaler()

In [11]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
mlp = MLPClassifier(hidden_layer_sizes=(60,90,120,90,60),max_iter=100000)

In [13]:
mlp.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(60, 90, 120, 90, 60), max_iter=100000)

In [14]:
predictions = mlp.predict(X_test)
print(predictions)
print(y_test)

[ 5  3 29  8  9  9  9 26  8 22  5 26  8  9  8 14  3  8 15 26  9  1  9  9
 18  8 11 27 16 29  5  9 18  9  9  9 28 27 28 18  8  8  8 11 11 26  8  3
 11  8 11  9 27 16  7  9  7 27 18  9  9 16  9  8 27 13  9 27  9  8  9 27
  9  3  9 18  9]
94      5
38      3
37     29
149     8
117     9
193     9
172     5
176    26
264     8
115    22
229     5
60     26
123     8
152     9
122     8
181    14
99      3
34     27
173    15
2      26
200     9
102     6
148     9
203     9
67     18
91     27
3      27
76     27
150    16
89     29
230     5
295     9
174    18
266     9
281     9
215     9
9      28
265    27
285    28
105    18
103     8
205     8
184     8
104    11
52     11
249    26
242     8
301     3
280     9
110     6
47     11
272     9
25     27
282    27
268     7
170     9
41      7
293    27
167    18
258     9
178     9
97     16
106     9
6       8
162    27
241    13
298     9
55     27
218     9
14      8
134     9
206    27
290     9
220     3
248     9
246    18
213 

In [15]:
print(confusion_matrix(y_test, predictions))

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 21  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  2  0  1  0  0  0  1  0  0  0  7  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0

In [16]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           3       1.00      1.00      1.00         4
           5       1.00      0.75      0.86         4
           6       0.00      0.00      0.00         2
           7       1.00      1.00      1.00         2
           8       0.77      1.00      0.87        10
           9       0.95      0.95      0.95        22
          11       0.60      1.00      0.75         3
          13       1.00      1.00      1.00         1
          14       1.00      1.00      1.00         1
          15       1.00      1.00      1.00         1
          16       0.67      1.00      0.80         2
          18       1.00      1.00      1.00         5
          22       1.00      1.00      1.00         1
          26       1.00      1.00      1.00         4
          27       1.00      0.64      0.78        11
          28       1.00      1.00      1.00         2
          29       1.00    

/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1

Day	Month	Year	Amount	Uber	Touchstone	United Airlines	McDonald's	Starbucks	Sparkfun	Tectra Inc	KFC	Madison Bicycle Shop	Categories

In [17]:
def parseDate(date):
    if date[8] == '0':
        day = date[9]
    else:     
        day = date[8:10]
    if date[5] == '0':
        month = date[6]
    else:
        month = date[5:7]
    year = date[:4]

    return day, month, year

# Opens transactions pulled from Plaid
def buildDataFrame(dataframe):
    with open("../newTransactions.json") as f:
        data = json.load(f)

    # Filters out only transactions that have a merchant_name 
    filtered_list = []
    for i in range(len(data)):
        if data[i]['merchant_name'] != None:
            print(data[i]['date'], data[i]['amount'], data[i]['name'])
            filtered_list.append(data[i])

    # Saves filtered list to a file to be used by front-end
    with open('../newFilteredTransactions.json', 'w') as jsonfile:
        json.dump(filtered_list, jsonfile)

    columns = {}
    # Labels dictionary for real data set
    subcategories = {'Mortgage': 1, 'Utilities': 2, 'Internet': 3, 'Home Repairs': 4, 'Gas': 5, 'Car Repairs': 6, 'Auto Insurance': 7, 'Groceries': 8, 'Fast Food': 9, 'Restaurants': 10, 'Beverages': 11, 'Pet Food & Supplies': 12, 'Veterinary': 13, 'Cell Phones': 14, 'Clothes': 15, 'Subscriptions': 16, 'Entertainment': 17, 'Life Insurance': 18, 'Pet Insurance': 19, 'Student Loans': 20, 'Home Equity Loan': 21, 'Home Depot Project Loan': 22, 'Cassie Capital One': 23, 'Braden Capital One': 24, 'Deseret First Credit': 25, 'Khols Credit': 26, 'MISC': 27, 'Pharmacy': 28, 'Dental & Vision Insurance': 29, 'Eyecare': 30, 'Doctor': 31}
    # Labels dictionary for sandbox data
    labels = {"Uber": 1, "Touchstone": 2, "United Airlines": 3, "McDonald's": 4, "Starbucks": 5, "Sparkfun": 6, "Tectra Inc": 7, "Madison Bicycle Shop": 8, "KFC": 4}
    
    categories = []
    df = pd.DataFrame(0, columns=dataframe.columns, index=dataframe.index)
    df = df[df.index < len(filtered_list)]
    df['Amount'] = df['Amount'].astype(float)
    for i in range(len(filtered_list)):
        currentItem = filtered_list[i]
        day, month, year = parseDate(currentItem['date'])
        amount = currentItem['amount']

        for col in df.columns:
            if col == 'Day':
                df['Day'].values[i] = day
            elif col == 'Month':
                df['Month'].values[i] = month 
            elif col == 'Year':
                df['Year'].values[i] = year
            elif col == 'Amount':
                df['Amount'].values[i] = amount
            elif col.lower() == currentItem['merchant_name'].lower() or col.lower() == currentItem['name'].lower():
                df[col].values[i] = 1
            else:
                df[col].values[i] = 0
            
    # count = 0
    # for i in range(0, len(filtered_list)):
    #     currentItem = filtered_list[i]
    
    #     if not currentItem['merchant_name'].__eq__('None'):
    #         day, month, year = parseDate(currentItem['date'])
    #         amount = currentItem['amount']
    #         df.loc[i] = [day, month, year, amount]

    #         # if currentItem['merchant_name'] not in columns:
    #         #     columns[currentItem['merchant_name']]=[1]
            
    #         #     for i in range(count):
    #         #         columns[currentItem['merchant_name']].insert(0,0)
    #         #     count += 1
                
    #         #     for key, value in columns.items():
    #         #         if not key.__eq__(currentItem['merchant_name']):
    #         #             value.append(0)
    #         # else:
    #         #     columns[currentItem['merchant_name']].append(1)
    #         #     count += 1
    #         #     for key, value in columns.items():
    #         #         if not key.__eq__(currentItem['merchant_name']):
    #         #             value.append(0)
    #         # categories.append(labels[currentItem['merchant_name']])

    # # Save dataframe as csv to add labels in excel
    # df.to_csv('newFilteredTransactions.csv')

    # Read labels from excel file, convert to numbers
    # Using dictionary and add as column to dataframe
    myDataSet = pd.read_excel('newFilteredTransactions.xlsx')
    for category in myDataSet['Categories']:
        categories.append(subcategories[category])

    # for column in columns:
    #     df[column] = columns[column]
    df['Categories'] = categories

    return df

In [18]:


small_batch = buildDataFrame(df)
# small_batch = small_batch.drop('Merchant Name', axis=1)
small_batch

2021-12-04 39.21 Chick-Fil-A
2021-12-04 292.79 PoS Withdrawal 844028311885 AT&T MOBILITY EPAY
2021-12-03 6.37 Chick-fil-A
2021-12-03 75 PoS Withdrawal 44557734199 THE EFT CLINIC STRIPE.COM
2021-12-03 10.27 Wendy's
2021-12-01 107.25 PoS Withdrawal 4445013508739 WWW.KOHLS.COM #0873
2021-11-30 2.77 7-Eleven
2021-11-30 390 ACH Withdrawal THD Loan Svcs 8669360602 - WEB PAY
2021-11-30 49.36 Chevron
2021-11-30 96.48 PoS Withdrawal 4445013508739 WWW.KOHLS.COM #0873
2021-11-30 15.87 Wendy's
2021-11-29 42.37 PoS Withdrawal 4445013508739 WWW.KOHLS.COM #0873
2021-11-29 150.05 PoS Withdrawal 4445013508739 WWW.KOHLS.COM #0873
2021-11-27 22 Great Clips
2021-11-27 136.43 PoS Withdrawal 4445013508739 WWW.KOHLS.COM #0873
2021-11-26 13.66 Chick-Fil-A
2021-11-26 61.1 PoS Withdrawal 9100000003376 TARGET 00033761
2021-11-26 10.48 PoS Withdrawal MACEY'S GRANGER 3555 WEST 3500 SOUTH WEST VALLEY CUTUS
2021-11-24 18.65 PoS Withdrawal 4445000679803 LITTLE CAESARS 011
2021-11-24 67.14 PoS Withdrawal 48206279993 S

Day  Month  Year  Amount  Home Mtg  Chevron  Kohl's  \
0     4     12  2021   39.21         0        0       0   
1     4     12  2021  292.79         0        0       0   
2     3     12  2021    6.37         0        0       0   
3     3     12  2021   75.00         0        0       0   
4     3     12  2021   10.27         0        0       0   
5     1     12  2021  107.25         0        0       0   
6    30     11  2021    2.77         0        0       0   
7    30     11  2021  390.00         0        0       0   
8    30     11  2021   49.36         0        1       0   
9    30     11  2021   96.48         0        0       0   
10   30     11  2021   15.87         0        0       0   
11   29     11  2021   42.37         0        0       0   
12   29     11  2021  150.05         0        0       0   
13   27     11  2021   22.00         0        0       0   
14   27     11  2021  136.43         0        0       0   
15   26     11  2021   13.66         0        0       0   
16   26     11  2021   61.10         0        0       0   
17   26     11  2021   10.48         0        0       0   
18   24     11  2021   18.65         0        0       0   
19   24     11  2021   67.14         0        0       0   
20   24     11  2021   44.47         0        0       0   
21   23     11  2021    6.41         0        0       0   
22   23     11  2021   58.10         0        0       0   
23   23     11  2021  100.00         0        0       0   
24   23     11  2021  175.83         0        0       0   
25   23     11  2021    0.99         0        0       0   
26   23     11  2021   37.00         0        0       0   
27   23     11  2021  162.03         0        0       0   
28   23     11  2021    9.83         0        0       0   
29   22     11  2021   10.23         0        0       0   
30   22     11  2021   30.50         0        0       0   
31   22     11  2021   30.00         0        0       0   
32   22     11  2021   14.03         0        0       0   
33   22     11  2021   21.18         0        0       0   

    Anything For A Friend  Arby's  Crumbl  Walmart  Amazon  CVS  \
0                       0       0       0        0       0    0   
1                       0       0       0        0       0    0   
2                       0       0       0        0       0    0   
3                       0       0       0        0       0    0   
4                       0       0       0        0       0    0   
5                       0       0       0        0       0    0   
6                       0       0       0        0       0    0   
7                       0       0       0        0       0    0   
8                       0       0       0        0       0    0   
9                       0       0       0        0       0    0   
10                      0       0       0        0       0    0   
11                      0       0       0        0       0    0   
12                      0       0       0        0       0    0   
13                      0       0       0        0       0    0   
14                      0       0       0        0       0    0   
15                      0       0       0        0       0    0   
16                      0       0       0        0       0    0   
17                      0       0       0        0       0    0   
18                      0       0       0        0       0    0   
19                      0       0       0        0       0    0   
20                      0       0       0        0       0    0   
21                      0       0       0        0       0    0   
22                      0       0       0        0       0    0   
23                      0       0       0        0       0    0   
24                      0       0       0        0       0    0   
25                      0       0       0        0       0    0   
26                      0       0       0        0       0    0   
27                      0       0       0        1       0    

In [19]:
# import random

# columns = ['Day', 'Month', 'Year', 'Amount', 'Uber', 'Touchstone', 'United Airlines', 'McDonald\'s', 'Starbucks', 'Sparkfun', 'Tectra Inc', 'KFC', 'Madison Bicycle Shop', 'Categories', 'Merchant']
# tf = pd.DataFrame(columns=columns)

# for i in range(25):
#     day = random.randint(1, 28)
#     month = random.randint(1, 12)
#     year = 2021
#     amount = round(random.uniform(-250, -.50), 2)

#     merchants = [0] * 10
#     randomIndex = random.randint(0,8)
#     merchants[randomIndex] = 1

#     if randomIndex == 7:
#         category = 4
#     elif randomIndex == 8:
#         category = 8
#     else:
#         category = randomIndex + 1

#     merchant_names = ['Uber', 'Touchstone', 'United Airlines', 'McDonald\'s', 'Starbucks', 'Sparkfun', 'Tectra Inc', 'KFC', 'Madison Bicycle Shop']

#     tf.loc[i] = [day, month, year, amount, merchants[0], merchants[1], merchants[2], merchants[3], merchants[4], merchants[5], merchants[6], merchants[7], merchants[8], category, merchant_names[randomIndex]]
# # tf = tf.astype(int)
# data = tf.to_json('newTransactions.json', orient='records')
# tf

In [20]:
# Read excel file into pandas dataframe
# small_batch = pd.read_excel('small_batch.xlsx')
# small_batch = tf
# small_batch

In [21]:
# Separate Label from transaction
X = small_batch.drop('Categories', axis=1)
# X = X.drop('Merchant', axis=1)
y = small_batch['Categories']

In [22]:
# Scale the data
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X)
StandardScaler(copy=True, with_mean=True, with_std=True)
# Now apply the transformations to the data:
X = scaler.transform(X)

In [23]:
predictions = mlp.predict(X)
y = y.astype(int)

In [24]:
print(confusion_matrix(y, predictions))

[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  1  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]]


In [25]:
for (predict, actual, score) in zip(predictions, y, mlp.predict_proba(X)):
    print("prediction: ", predict, "actual: ", actual, "confidence: ", score)

prediction:  9 actual:  9 confidence:  [6.52141791e-05 3.02721048e-05 3.64121951e-05 2.52832806e-05
 1.81524174e-04 2.18730307e-03 9.73015340e-06 1.91453984e-03
 8.47442725e-01 3.70359491e-03 1.23672901e-01 3.27407660e-04
 1.44021416e-04 3.73285842e-04 4.33488570e-03 5.19356752e-03
 1.77338553e-04 2.81793533e-04 9.67502090e-06 3.20721995e-04
 8.09937612e-03 6.54785545e-04 2.01721859e-05 7.93469274e-04]
prediction:  14 actual:  14 confidence:  [4.08321493e-04 2.05847714e-04 3.05354144e-06 3.27578095e-03
 2.52451902e-04 6.71428845e-06 1.66668758e-05 1.20276761e-05
 1.54521402e-04 4.99576117e-08 1.52190284e-06 4.11710233e-05
 1.60728135e-06 9.92333193e-01 4.85133918e-09 3.22597746e-04
 1.70264969e-04 1.30349629e-03 2.20357096e-07 9.62084898e-06
 1.80705759e-06 9.40549629e-05 1.02740511e-03 3.57598702e-04]
prediction:  9 actual:  9 confidence:  [3.76398705e-05 1.53466386e-05 2.02106069e-05 1.48369870e-05
 9.68439285e-05 1.69259010e-03 5.16971475e-06 9.19076277e-04
 8.35897008e-01 2.7992189

In [32]:
# for (i, predict, actual, score) in zip(y.index, predictions, y, mlp.predict_proba(X)):
#     print("DataPoint: ", i, "prediction: ", predict, "actual: ", actual, "confidence: ", score)

array = mlp.predict_proba(X).tolist()


def topThreeIndices(array):
    topThree = []
    second_array = []
    # Make deep copy of array
    for i in range(len(array)):
        second_array.append(0)
        second_array[i] = array[i]
    for i in range(3):
        max_value = max(second_array)
        max_index = array.index(max_value)
        topThree.append(max_index + 1)
        second_array.remove(max_value)
    return topThree

results = []
for predictions in array:
    result = topThreeIndices(predictions)
    results.append(result)

with open('NeuralNetworkPredictions.json', 'w') as jsonfile:
    json_results = {}
    json_results["Predictions"] = results
    json.dump(json_results, jsonfile)

max_value = max(array[0])
max_index = array[0].index(max_value)
