In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import json

In [2]:
# Read csv file into pandas dataframe
transactions = pd.read_excel('FoodUtilitiesGroceriesGas.xlsx')
transactions

Day  Month  Year  Amount  Five Guys  In N Out  Chick-Fil-A  \
0      4      9  2021  -63.77          0         0            0   
1      3      9  2021  -22.76          0         0            1   
2      3      9  2021  -17.12          0         0            0   
3      3      9  2021 -124.07          0         0            0   
4      2      9  2021  -16.51          0         0            0   
..   ...    ...   ...     ...        ...       ...          ...   
587   14     11  2019  -12.74          0         0            0   
588   13     11  2019  -11.92          0         0            0   
589   12     11  2019   -7.82          0         0            0   
590   12     11  2019  -12.18          0         0            0   
591   12     11  2019 -174.26          0         0            0   

     Little Caesars  Cafe Rio  Taco Bell  ...  Fast Stop  Capital One - B  \
0                 0         0          0  ...          0                0   
1                 0         0          0  ...          0                0   
2                 0         0          0  ...          0                0   
3                 0         0          0  ...          0                0   
4                 0         0          0  ...          0                0   
..              ...       ...        ...  ...        ...              ...   
587               0         0          0  ...          0                0   
588               0         0          0  ...          0                0   
589               0         0          0  ...          0                0   
590               0         0          0  ...          0                0   
591               0         0          0  ...          0                0   

     Capital One - C  Progressive  US Bank  Deseret First  THD Loan Svcs  \
0                  0            0        0              0              0   
1                  0            0        0              0              0   
2                  0            0        0              0              0   
3                  0            0        0              0              0   
4                  0            0        0              0              0   
..               ...          ...      ...            ...            ...   
587                0            0        0              0              0   
588                0            0        0              0              0   
589                0            0        0              0              0   
590                0            0        0              0              0   
591                0            0        0              0              0   

     KOHL'S TELECHK  Count  Categories  
0                 0     72           4  
1                 0    194           1  
2                 0    103           3  
3                 0    103           3  
4                 0    194           1  
..              ...    ...         ...  
587               0    103           3  
588               0     72           4  
589               0    103           3  
590               0     72           4  
591               0    103           3  

[592 rows x 66 columns]

In [3]:
from dataFrameBuilder import buildDataFrame
# pd.set_option("display.max_rows", None, "display.max_columns", None)

df = buildDataFrame()
df = df.drop('Merchant Name', axis=1)
df

2021-11-06 5.4 Uber 063015 SF**POOL**
2021-11-04 78.5 Touchstone Climbing
2021-11-04 -500 United Airlines
2021-11-03 12 McDonald's
2021-11-03 4.33 Starbucks
2021-11-02 89.4 SparkFun
2021-10-22 500 United Airlines
2021-10-20 6.33 Uber 072515 SF**POOL**
2021-10-17 500 Tectra Inc
2021-10-16 500 KFC
2021-10-16 500 Madison Bicycle Shop
2021-10-07 5.4 Uber 063015 SF**POOL**
2021-10-05 78.5 Touchstone Climbing
2021-10-05 -500 United Airlines
2021-10-04 12 McDonald's
2021-10-04 4.33 Starbucks
2021-10-03 89.4 SparkFun
2021-09-22 500 United Airlines
2021-09-20 6.33 Uber 072515 SF**POOL**
2021-09-17 500 Tectra Inc
2021-09-16 500 KFC
2021-09-16 500 Madison Bicycle Shop
2021-09-07 5.4 Uber 063015 SF**POOL**
2021-09-05 78.5 Touchstone Climbing
2021-09-05 -500 United Airlines
2021-09-04 12 McDonald's
2021-09-04 4.33 Starbucks
2021-09-03 89.4 SparkFun
2021-08-23 500 United Airlines
2021-08-21 6.33 Uber 072515 SF**POOL**
2021-08-18 500 Tectra Inc
2021-08-17 500 KFC
2021-08-17 500 Madison Bicycle Shop
2

Day Month  Year  Amount  Uber  Touchstone  United Airlines  McDonald's  \
0     6    11  2021    5.40     1           0                0           0   
1     4    11  2021   78.50     0           1                0           0   
2     4    11  2021 -500.00     0           0                1           0   
3     3    11  2021   12.00     0           0                0           1   
4     3    11  2021    4.33     0           0                0           0   
..   ..   ...   ...     ...   ...         ...              ...         ...   
257  14    12  2019    4.33     0           0                0           0   
258  13    12  2019   89.40     0           0                0           0   
259   2    12  2019  500.00     0           0                1           0   
260  30    11  2019    6.33     1           0                0           0   
261  27    11  2019  500.00     0           0                0           0   

     Starbucks  Sparkfun  Tectra Inc  KFC  Madison Bicycle Shop  Categories  
0            0         0           0    0                     0           1  
1            0         0           0    0                     0           2  
2            0         0           0    0                     0           3  
3            0         0           0    0                     0           4  
4            1         0           0    0                     0           5  
..         ...       ...         ...  ...                   ...         ...  
257          1         0           0    0                     0           5  
258          0         1           0    0                     0           6  
259          0         0           0    0                     0           3  
260          0         0           0    0                     0           1  
261          0         0           1    0                     0           7  

[262 rows x 14 columns]

In [4]:
transactions.describe().transpose()

count         mean         std      min     25%      50%  \
Day             592.0    16.021959    8.435353     1.00     9.0    16.00   
Month           592.0     5.746622    3.130007     1.00     3.0     5.00   
Year            592.0  2020.525338    0.551294  2019.00  2020.0  2021.00   
Amount          592.0   -73.716503  115.621845  -909.83   -85.6   -30.89   
Five Guys       592.0     0.043919    0.205088     0.00     0.0     0.00   
...               ...          ...         ...      ...     ...      ...   
Deseret First   592.0     0.070946    0.256952     0.00     0.0     0.00   
THD Loan Svcs   592.0     0.030405    0.171845     0.00     0.0     0.00   
KOHL'S TELECHK  592.0     0.018581    0.135154     0.00     0.0     0.00   
Count           592.0    96.692568   74.731692     5.00    19.0   103.00   
Categories      592.0     3.559122    3.066088     1.00     1.0     3.00   

                      75%      max  
Day               23.0000    31.00  
Month              8.0000    12.00  
Year            2021.0000  2021.00  
Amount           -16.8925    -0.54  
Five Guys          0.0000     1.00  
...                   ...      ...  
Deseret First      0.0000     1.00  
THD Loan Svcs      0.0000     1.00  
KOHL'S TELECHK     0.0000     1.00  
Count            194.0000   194.00  
Categories         4.0000    12.00  

[66 rows x 8 columns]

In [5]:
transactions = df

In [6]:
X = transactions.drop('Categories', axis=1)
y = transactions['Categories']


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
print(len(X_train), len(X_test))


196 66


In [8]:
scaler = StandardScaler()

In [9]:
# Fit only to the training data
scaler.fit(X_train)

StandardScaler()

In [10]:
StandardScaler(copy=True, with_mean=True, with_std=True)

StandardScaler()

In [11]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
mlp = MLPClassifier(hidden_layer_sizes=(60,90,120,90,60),max_iter=100000)

In [13]:
mlp.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(60, 90, 120, 90, 60), max_iter=100000)

In [14]:
predictions = mlp.predict(X_test)
print(predictions)
print(y_test.index)

[7 7 4 4 2 4 4 3 6 3 1 1 3 8 3 6 5 5 8 8 4 6 4 6 5 5 1 7 3 3 8 4 5 4 3 3 2
 5 4 1 1 3 1 1 1 1 3 1 2 7 2 3 2 4 1 6 6 8 5 8 8 5 8 3 3 2]
Int64Index([ 52,   8,  69, 218, 199, 240, 234, 215, 104, 138, 143,  51,  68,
             98, 193, 115, 169, 191, 252,  43, 146, 258,  80,  60,  59, 103,
            253, 118,  79,  83, 230, 135,  37, 108, 112, 182,  45, 147,  47,
            209,  11,  28, 194,  66,  88,  40, 116, 220, 221, 228,  89, 160,
             67, 113, 231, 181, 225, 153,  81,  54,  76,   4, 241,  50, 259,
            243],
           dtype='int64')


In [15]:
print(confusion_matrix(y_test, predictions))

[[11  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0]
 [ 0  0 13  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0]
 [ 0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  6  0  0]
 [ 0  0  0  0  0  0  4  0]
 [ 0  0  0  0  0  0  0  8]]


In [16]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         6
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00        10
           5       1.00      1.00      1.00         8
           6       1.00      1.00      1.00         6
           7       1.00      1.00      1.00         4
           8       1.00      1.00      1.00         8

    accuracy                           1.00        66
   macro avg       1.00      1.00      1.00        66
weighted avg       1.00      1.00      1.00        66



In [17]:
predictions = mlp.predict(X)

for (i, predict, actual, score) in zip(y.index, predictions, y, mlp.predict_proba(X)):
    print("DataPoint: ", i, "prediction: ", predict, "actual: ", actual, "confidence: ", score)

array = mlp.predict_proba(X).tolist()


def topThreeIndices(array):
    topThree = []
    second_array = []
    # Make deep copy of array
    for i in range(len(array)):
        second_array.append(0)
        second_array[i] = array[i]
    for i in range(3):
        max_value = max(second_array)
        max_index = array.index(max_value)
        topThree.append(max_index)
        second_array.remove(max_value)
    return topThree

results = []
for predictions in array:
    result = topThreeIndices(predictions)
    results.append(result)

with open('NeuralNetworkPredictions.json', 'w') as jsonfile:
    json_results = {}
    json_results["Predictions"] = results
    json.dump(json_results, jsonfile)


DataPoint:  0 prediction:  4 actual:  1 confidence:  [7.07913943e-104 0.00000000e+000 1.69887070e-064 1.00000000e+000
 0.00000000e+000 1.26449644e-210 0.00000000e+000 0.00000000e+000]
DataPoint:  1 prediction:  4 actual:  2 confidence:  [3.31548159e-133 0.00000000e+000 9.66872993e-063 1.00000000e+000
 0.00000000e+000 9.59249777e-252 0.00000000e+000 0.00000000e+000]
DataPoint:  2 prediction:  1 actual:  3 confidence:  [9.99997569e-001 4.01769936e-239 8.08457617e-123 2.76079421e-051
 0.00000000e+000 2.43139435e-006 0.00000000e+000 0.00000000e+000]
DataPoint:  3 prediction:  4 actual:  4 confidence:  [4.32140152e-109 0.00000000e+000 4.10421034e-066 1.00000000e+000
 0.00000000e+000 2.62987920e-214 0.00000000e+000 0.00000000e+000]
DataPoint:  4 prediction:  4 actual:  5 confidence:  [1.55084557e-105 0.00000000e+000 3.65921432e-066 1.00000000e+000
 0.00000000e+000 2.19448341e-209 0.00000000e+000 0.00000000e+000]
DataPoint:  5 prediction:  4 actual:  6 confidence:  [1.85194019e-139 0.00000000

In [18]:
# Read excel file into pandas dataframe
small_batch = pd.read_excel('small_batch.xlsx')
small_batch = transactions[:10]
small_batch

Day Month  Year  Amount  Uber  Touchstone  United Airlines  McDonald's  \
0   6    11  2021    5.40     1           0                0           0   
1   4    11  2021   78.50     0           1                0           0   
2   4    11  2021 -500.00     0           0                1           0   
3   3    11  2021   12.00     0           0                0           1   
4   3    11  2021    4.33     0           0                0           0   
5   2    11  2021   89.40     0           0                0           0   
6  22    10  2021  500.00     0           0                1           0   
7  20    10  2021    6.33     1           0                0           0   
8  17    10  2021  500.00     0           0                0           0   
9  16    10  2021  500.00     0           0                0           0   

   Starbucks  Sparkfun  Tectra Inc  KFC  Madison Bicycle Shop  Categories  
0          0         0           0    0                     0           1  
1          0         0           0    0                     0           2  
2          0         0           0    0                     0           3  
3          0         0           0    0                     0           4  
4          1         0           0    0                     0           5  
5          0         1           0    0                     0           6  
6          0         0           0    0                     0           3  
7          0         0           0    0                     0           1  
8          0         0           1    0                     0           7  
9          0         0           0    1                     0           4

In [19]:
# Separate Label from transaction
X = small_batch.drop('Categories', axis=1)
y = small_batch['Categories']

In [20]:
# Scale the data
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X)
StandardScaler(copy=True, with_mean=True, with_std=True)
# Now apply the transformations to the data:
X = scaler.transform(X)

In [21]:
predictions = mlp.predict(X)
predictions

array([1, 2, 3, 4, 5, 6, 3, 1, 7, 4])

In [22]:
print(confusion_matrix(y, predictions))

[[2 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


In [23]:
for (predict, actual, score) in zip(predictions, y, mlp.predict_proba(X)):
    print("prediction: ", predict, "actual: ", actual, "confidence: ", score)

prediction:  1 actual:  1 confidence:  [9.99560761e-01 1.35613911e-04 2.14866896e-05 1.12734786e-04
 1.58432745e-07 1.67526841e-04 3.24295087e-07 1.39395386e-06]
prediction:  2 actual:  2 confidence:  [6.41040428e-05 9.99617914e-01 7.47019467e-07 4.80804753e-06
 9.13990120e-06 4.59239886e-05 2.49872781e-04 7.49008627e-06]
prediction:  3 actual:  3 confidence:  [5.58655139e-05 2.03184349e-06 9.99741304e-01 5.92450880e-05
 1.28120613e-04 7.45623132e-06 3.52143817e-06 2.45478975e-06]
prediction:  4 actual:  4 confidence:  [2.21001523e-06 2.85631313e-07 2.30947050e-06 9.99987305e-01
 3.93483092e-08 1.34898408e-06 6.71610460e-07 5.82991300e-06]
prediction:  5 actual:  5 confidence:  [8.86523831e-07 1.23250885e-05 4.81868420e-05 1.43063579e-05
 9.99620316e-01 3.62950891e-06 2.58251824e-04 4.20975352e-05]
prediction:  6 actual:  6 confidence:  [1.42065981e-04 3.55836664e-05 2.83599099e-06 6.23862416e-06
 1.23776356e-05 9.99686551e-01 1.14341442e-04 5.41704923e-09]
prediction:  3 actual:  3 co

In [24]:
with open("../transactions.json") as f:
    data = json.load(f)

In [25]:
df = pd.DataFrame(columns=["amount", "date", "merchant_name"])
for i in range(0, len(data)):
    currentItem = data[i]
    df.loc[i] = [data[i]["amount"], data[i]["date"], data[i]["merchant_name"]]

In [26]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
batch = df.iloc[:2]
batch

amount        date merchant_name
0     25  2021-11-06          None
1    5.4  2021-11-06          Uber

In [27]:
pandas_df = pd.DataFrame(columns=["Day", "Month", "Year", "Amount", "FiveGuys", "InNout", "Chick-Fil-A", "LittleCaesars", "CafeRio", "TacoBell", "Chipotle", "Wendys", "Arbys", "BurgerKing", "McDonalds", "ArcticCircle", "Sonic", "Rancheritos", "MesqMexGrill", "FlyingPiePizzeria", "JimmyJohns", "FreeBirds", "PandaExp", "Moochies", "PizzaHut", "CalMexFood", "Kneaders", "Jamba", "UVending", "Crumbl", "RockyMountainPower", "QuestarGas", "GrangerHunter", "WVCC", "UtahInfras", "Xmission", "Walgreens", "Winco", "Walmart", "Lucky", "SamsClub", "Maceys", "Davis", "Harmons", "Reams", "Smiths", "Albertons", "FreshMarket", "NPS", "EarthGrains", "Chevron", "Shell", "CostcoGas", "Maverik", "7-Eleven", "HarmonsGas", "FastStop", "CapitalOne-B", "CapitalOne-C", "Progressive", "USBank", "DFCU", "ThdLoanSvcs", "KholsTelechk", "Count", "Categories"])
pandas_df

Empty DataFrame
Columns: [Day, Month, Year, Amount, FiveGuys, InNout, Chick-Fil-A, LittleCaesars, CafeRio, TacoBell, Chipotle, Wendys, Arbys, BurgerKing, McDonalds, ArcticCircle, Sonic, Rancheritos, MesqMexGrill, FlyingPiePizzeria, JimmyJohns, FreeBirds, PandaExp, Moochies, PizzaHut, CalMexFood, Kneaders, Jamba, UVending, Crumbl, RockyMountainPower, QuestarGas, GrangerHunter, WVCC, UtahInfras, Xmission, Walgreens, Winco, Walmart, Lucky, SamsClub, Maceys, Davis, Harmons, Reams, Smiths, Albertons, FreshMarket, NPS, EarthGrains, Chevron, Shell, CostcoGas, Maverik, 7-Eleven, HarmonsGas, FastStop, CapitalOne-B, CapitalOne-C, Progressive, USBank, DFCU, ThdLoanSvcs, KholsTelechk, Count, Categories]
Index: []

In [28]:
for i in range(len(batch)):
    date = batch['date'][i]
    year = date[:4]
    month = date[5:7]
    day = date[8:10]
    pandas_df.at[i, 'Day'] = day
    pandas_df.at[i, 'Month'] = month
    pandas_df.at[i, 'Year'] = year
    
pandas_df


Day Month  Year Amount FiveGuys InNout Chick-Fil-A LittleCaesars CafeRio  \
0  06    11  2021    NaN      NaN    NaN         NaN           NaN     NaN   
1  06    11  2021    NaN      NaN    NaN         NaN           NaN     NaN   

  TacoBell Chipotle Wendys Arbys BurgerKing McDonalds ArcticCircle Sonic  \
0      NaN      NaN    NaN   NaN        NaN       NaN          NaN   NaN   
1      NaN      NaN    NaN   NaN        NaN       NaN          NaN   NaN   

  Rancheritos MesqMexGrill FlyingPiePizzeria JimmyJohns FreeBirds PandaExp  \
0         NaN          NaN               NaN        NaN       NaN      NaN   
1         NaN          NaN               NaN        NaN       NaN      NaN   

  Moochies PizzaHut CalMexFood Kneaders Jamba UVending Crumbl  \
0      NaN      NaN        NaN      NaN   NaN      NaN    NaN   
1      NaN      NaN        NaN      NaN   NaN      NaN    NaN   

  RockyMountainPower QuestarGas GrangerHunter WVCC UtahInfras Xmission  \
0                NaN        NaN           NaN  NaN        NaN      NaN   
1                NaN        NaN           NaN  NaN        NaN      NaN   

  Walgreens Winco Walmart Lucky SamsClub Maceys Davis Harmons Reams Smiths  \
0       NaN   NaN     NaN   NaN      NaN    NaN   NaN     NaN   NaN    NaN   
1       NaN   NaN     NaN   NaN      NaN    NaN   NaN     NaN   NaN    NaN   

  Albertons FreshMarket  NPS EarthGrains Chevron Shell CostcoGas Maverik  \
0       NaN         NaN  NaN         NaN     NaN   NaN       NaN     NaN   
1       NaN         NaN  NaN         NaN     NaN   NaN       NaN     NaN   

  7-Eleven HarmonsGas FastStop CapitalOne-B CapitalOne-C Progressive USBank  \
0      NaN        NaN      NaN          NaN          NaN         NaN    NaN   
1      NaN        NaN      NaN          NaN          NaN         NaN    NaN   

  DFCU ThdLoanSvcs KholsTelechk Count Categories  
0  NaN         NaN          NaN   NaN        NaN  
1  NaN         NaN          NaN   NaN        NaN