In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import json

In [2]:
# Read csv file into pandas dataframe
transactions = pd.read_excel('FoodUtilitiesGroceriesGas.xlsx')
transactions

Day  Month  Year  Amount  Five Guys  In N Out  Chick-Fil-A  \
0      4      9  2021  -63.77          0         0            0   
1      3      9  2021  -22.76          0         0            1   
2      3      9  2021  -17.12          0         0            0   
3      3      9  2021 -124.07          0         0            0   
4      2      9  2021  -16.51          0         0            0   
..   ...    ...   ...     ...        ...       ...          ...   
587   14     11  2019  -12.74          0         0            0   
588   13     11  2019  -11.92          0         0            0   
589   12     11  2019   -7.82          0         0            0   
590   12     11  2019  -12.18          0         0            0   
591   12     11  2019 -174.26          0         0            0   

     Little Caesars  Cafe Rio  Taco Bell  ...  Fast Stop  Capital One - B  \
0                 0         0          0  ...          0                0   
1                 0         0          0  ...          0                0   
2                 0         0          0  ...          0                0   
3                 0         0          0  ...          0                0   
4                 0         0          0  ...          0                0   
..              ...       ...        ...  ...        ...              ...   
587               0         0          0  ...          0                0   
588               0         0          0  ...          0                0   
589               0         0          0  ...          0                0   
590               0         0          0  ...          0                0   
591               0         0          0  ...          0                0   

     Capital One - C  Progressive  US Bank  Deseret First  THD Loan Svcs  \
0                  0            0        0              0              0   
1                  0            0        0              0              0   
2                  0            0        0              0              0   
3                  0            0        0              0              0   
4                  0            0        0              0              0   
..               ...          ...      ...            ...            ...   
587                0            0        0              0              0   
588                0            0        0              0              0   
589                0            0        0              0              0   
590                0            0        0              0              0   
591                0            0        0              0              0   

     KOHL'S TELECHK  Count  Categories  
0                 0     72           4  
1                 0    194           1  
2                 0    103           3  
3                 0    103           3  
4                 0    194           1  
..              ...    ...         ...  
587               0    103           3  
588               0     72           4  
589               0    103           3  
590               0     72           4  
591               0    103           3  

[592 rows x 66 columns]

In [3]:
from dataFrameBuilder import buildDataFrame
# pd.set_option("display.max_rows", None, "display.max_columns", None)

df = buildDataFrame()
df = df.drop('Merchant Name', axis=1)
df

Day Month  Year  Amount  Chevron  Walmart  Target  The Eft Clinic  AT&T  \
1    10    11  2021   57.83        1        0       0               0     0   
3    10    11  2021    6.14        0        1       0               0     0   
6     8    11  2021   40.54        1        0       0               0     0   
8     6    11  2021    8.93        0        0       1               0     0   
9     5    11  2021   75.00        0        0       0               1     0   
..   ..   ...   ...     ...      ...      ...     ...             ...   ...   
493  17     5  2021   40.72        0        0       0               0     0   
496  17     5  2021   30.37        0        0       0               0     0   
497  15     5  2021   24.44        0        0       0               0     0   
498  14     5  2021    4.82        0        0       0               0     0   
499  14     5  2021   34.04        0        0       0               0     0   

     Harmons  ...  Varsity Tutors  In-N-Out Burger  Petco  \
1          0  ...               0                0      0   
3          0  ...               0                0      0   
6          0  ...               0                0      0   
8          0  ...               0                0      0   
9          0  ...               0                0      0   
..       ...  ...             ...              ...    ...   
493        0  ...               0                0      0   
496        0  ...               0                0      0   
497        0  ...               0                0      0   
498        0  ...               0                0      0   
499        0  ...               0                0      0   

     Smoky Mountain Pizza & Eagle  Tremonton  Oculus  Jimmy John's  \
1                               0          0       0             0   
3                               0          0       0             0   
6                               0          0       0             0   
8                               0          0       0             0   
9                               0          0       0             0   
..                            ...        ...     ...           ...   
493                             0          0       0             0   
496                             0          0       0             0   
497                             0          0       0             0   
498                             0          0       0             0   
499                             0          0       0             0   

     U.S. Post Office  Sonic  Steam Games  
1                   0      0            0  
3                   0      0            0  
6                   0      0            0  
8                   0      0            0  
9                   0      0            0  
..                ...    ...          ...  
493                 0      0            0  
496                 0      0            0  
497                 0      0            0  
498                 0      0            0  
499                 0      0            0  

[357 rows x 91 columns]

In [4]:
transactions.describe().transpose()

count         mean         std      min     25%      50%  \
Day             592.0    16.021959    8.435353     1.00     9.0    16.00   
Month           592.0     5.746622    3.130007     1.00     3.0     5.00   
Year            592.0  2020.525338    0.551294  2019.00  2020.0  2021.00   
Amount          592.0   -73.716503  115.621845  -909.83   -85.6   -30.89   
Five Guys       592.0     0.043919    0.205088     0.00     0.0     0.00   
...               ...          ...         ...      ...     ...      ...   
Deseret First   592.0     0.070946    0.256952     0.00     0.0     0.00   
THD Loan Svcs   592.0     0.030405    0.171845     0.00     0.0     0.00   
KOHL'S TELECHK  592.0     0.018581    0.135154     0.00     0.0     0.00   
Count           592.0    96.692568   74.731692     5.00    19.0   103.00   
Categories      592.0     3.559122    3.066088     1.00     1.0     3.00   

                      75%      max  
Day               23.0000    31.00  
Month              8.0000    12.00  
Year            2021.0000  2021.00  
Amount           -16.8925    -0.54  
Five Guys          0.0000     1.00  
...                   ...      ...  
Deseret First      0.0000     1.00  
THD Loan Svcs      0.0000     1.00  
KOHL'S TELECHK     0.0000     1.00  
Count            194.0000   194.00  
Categories         4.0000    12.00  

[66 rows x 8 columns]

In [5]:
transactions = df

In [6]:
X = transactions.drop('Categories', axis=1)
y = transactions['Categories']


KeyError: "['Categories'] not found in axis"

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
print(len(X_train), len(X_test))


128 43


In [ ]:
scaler = StandardScaler()

In [ ]:
# Fit only to the training data
scaler.fit(X_train)

StandardScaler()

In [ ]:
StandardScaler(copy=True, with_mean=True, with_std=True)

StandardScaler()

In [ ]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes=(60,90,120,90,60),max_iter=100000)

In [ ]:
mlp.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(60, 90, 120, 90, 60), max_iter=100000)

In [ ]:
predictions = mlp.predict(X_test)
predictions

array([2, 2, 7, 7, 1, 1, 8, 6, 3, 6, 4, 1, 8, 1, 4, 4, 5, 3, 3, 6, 1, 1,
       6, 3, 4, 5, 3, 2, 1, 1, 6, 6, 3, 4, 4, 4, 3, 1, 4, 3, 1, 2, 1])

In [ ]:
print(confusion_matrix(y_test, predictions))

[[11  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0]
 [ 0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  6  0  0]
 [ 0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  2]]


In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         8
           4       1.00      1.00      1.00         8
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         6
           7       1.00      1.00      1.00         2
           8       1.00      1.00      1.00         2

    accuracy                           1.00        43
   macro avg       1.00      1.00      1.00        43
weighted avg       1.00      1.00      1.00        43



In [ ]:
# Read excel file into pandas dataframe
small_batch = pd.read_excel('small_batch.xlsx')
small_batch = transactions[:10]
small_batch

Day Month  Year  Amount  Uber  Touchstone  United Airlines  McDonald's  \
1    6    11  2021    5.40     1           0                0           0   
4    4    11  2021   78.50     0           1                0           0   
5    4    11  2021 -500.00     0           0                1           0   
6    3    11  2021   12.00     0           0                0           1   
7    3    11  2021    4.33     0           0                0           0   
8    2    11  2021   89.40     0           0                0           0   
10  22    10  2021  500.00     0           0                1           0   
11  20    10  2021    6.33     1           0                0           0   
12  17    10  2021  500.00     0           0                0           0   
14  16    10  2021  500.00     0           0                0           0   

    Starbucks  Sparkfun  Tectra Inc  KFC  Madison Bicycle Shop  Categories  
1           0         0           0    0                     0           1  
4           0         0           0    0                     0           2  
5           0         0           0    0                     0           3  
6           0         0           0    0                     0           4  
7           1         0           0    0                     0           5  
8           0         1           0    0                     0           6  
10          0         0           0    0                     0           3  
11          0         0           0    0                     0           1  
12          0         0           1    0                     0           7  
14          0         0           0    1                     0           4

In [ ]:
# Separate Label from transaction
X = small_batch.drop('Categories', axis=1)
y = small_batch['Categories']

In [ ]:
# Scale the data
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X)
StandardScaler(copy=True, with_mean=True, with_std=True)
# Now apply the transformations to the data:
X = scaler.transform(X)

In [ ]:
prediction = mlp.predict(X)
prediction

array([1, 2, 3, 4, 5, 6, 3, 1, 7, 4])

In [ ]:
print(confusion_matrix(y, prediction))

[[2 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


In [ ]:
for (predict, actual, score) in zip(prediction, y, mlp.predict_proba(X)):
    print("prediction: ", predict, "actual: ", actual, "confidence: ", score)

prediction:  1 actual:  1 confidence:  [9.99601313e-01 1.63101228e-05 3.79836748e-07 2.82473900e-04
 9.70900055e-05 1.54696292e-06 3.43041802e-08 8.51633372e-07]
prediction:  2 actual:  2 confidence:  [9.56241714e-06 9.99353326e-01 4.52004078e-05 7.44207995e-06
 1.51428177e-04 3.50638118e-04 8.06858484e-05 1.71695912e-06]
prediction:  3 actual:  3 confidence:  [5.70474902e-10 3.45010635e-06 9.99937595e-01 2.54799797e-05
 2.50830046e-05 7.90991508e-06 3.63348577e-08 4.44864554e-07]
prediction:  4 actual:  4 confidence:  [5.74714046e-05 8.69949033e-06 2.75795543e-04 9.99564358e-01
 5.03103987e-05 4.24004225e-05 7.18124929e-08 8.93048782e-07]
prediction:  5 actual:  5 confidence:  [7.57720635e-07 9.32193916e-06 5.42845858e-05 1.51252220e-05
 9.99746476e-01 1.30977344e-04 4.36529679e-08 4.30138320e-05]
prediction:  6 actual:  6 confidence:  [6.56357860e-07 1.73914241e-04 4.44586345e-05 1.05451390e-04
 3.47348422e-04 9.99114955e-01 9.81846891e-06 2.03397909e-04]
prediction:  3 actual:  3 co

In [ ]:
with open("../transactions.json") as f:
    data = json.load(f)

In [ ]:
df = pd.DataFrame(columns=["amount", "date", "merchant_name"])
for i in range(0, len(data)):
    currentItem = data[i]
    df.loc[i] = [data[i]["amount"], data[i]["date"], data[i]["merchant_name"]]

In [ ]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
batch = df.iloc[:2]
batch

amount        date merchant_name
0     25  2021-11-06          None
1    5.4  2021-11-06          Uber

In [ ]:
pandas_df = pd.DataFrame(columns=["Day", "Month", "Year", "Amount", "FiveGuys", "InNout", "Chick-Fil-A", "LittleCaesars", "CafeRio", "TacoBell", "Chipotle", "Wendys", "Arbys", "BurgerKing", "McDonalds", "ArcticCircle", "Sonic", "Rancheritos", "MesqMexGrill", "FlyingPiePizzeria", "JimmyJohns", "FreeBirds", "PandaExp", "Moochies", "PizzaHut", "CalMexFood", "Kneaders", "Jamba", "UVending", "Crumbl", "RockyMountainPower", "QuestarGas", "GrangerHunter", "WVCC", "UtahInfras", "Xmission", "Walgreens", "Winco", "Walmart", "Lucky", "SamsClub", "Maceys", "Davis", "Harmons", "Reams", "Smiths", "Albertons", "FreshMarket", "NPS", "EarthGrains", "Chevron", "Shell", "CostcoGas", "Maverik", "7-Eleven", "HarmonsGas", "FastStop", "CapitalOne-B", "CapitalOne-C", "Progressive", "USBank", "DFCU", "ThdLoanSvcs", "KholsTelechk", "Count", "Categories"])
pandas_df

Empty DataFrame
Columns: [Day, Month, Year, Amount, FiveGuys, InNout, Chick-Fil-A, LittleCaesars, CafeRio, TacoBell, Chipotle, Wendys, Arbys, BurgerKing, McDonalds, ArcticCircle, Sonic, Rancheritos, MesqMexGrill, FlyingPiePizzeria, JimmyJohns, FreeBirds, PandaExp, Moochies, PizzaHut, CalMexFood, Kneaders, Jamba, UVending, Crumbl, RockyMountainPower, QuestarGas, GrangerHunter, WVCC, UtahInfras, Xmission, Walgreens, Winco, Walmart, Lucky, SamsClub, Maceys, Davis, Harmons, Reams, Smiths, Albertons, FreshMarket, NPS, EarthGrains, Chevron, Shell, CostcoGas, Maverik, 7-Eleven, HarmonsGas, FastStop, CapitalOne-B, CapitalOne-C, Progressive, USBank, DFCU, ThdLoanSvcs, KholsTelechk, Count, Categories]
Index: []

In [ ]:
for i in range(len(batch)):
    date = batch['date'][i]
    year = date[:4]
    month = date[5:7]
    day = date[8:10]
    pandas_df.at[i, 'Day'] = day
    pandas_df.at[i, 'Month'] = month
    pandas_df.at[i, 'Year'] = year
    
pandas_df


Day Month  Year Amount FiveGuys InNout Chick-Fil-A LittleCaesars CafeRio  \
0  06    11  2021    NaN      NaN    NaN         NaN           NaN     NaN   
1  06    11  2021    NaN      NaN    NaN         NaN           NaN     NaN   

  TacoBell Chipotle Wendys Arbys BurgerKing McDonalds ArcticCircle Sonic  \
0      NaN      NaN    NaN   NaN        NaN       NaN          NaN   NaN   
1      NaN      NaN    NaN   NaN        NaN       NaN          NaN   NaN   

  Rancheritos MesqMexGrill FlyingPiePizzeria JimmyJohns FreeBirds PandaExp  \
0         NaN          NaN               NaN        NaN       NaN      NaN   
1         NaN          NaN               NaN        NaN       NaN      NaN   

  Moochies PizzaHut CalMexFood Kneaders Jamba UVending Crumbl  \
0      NaN      NaN        NaN      NaN   NaN      NaN    NaN   
1      NaN      NaN        NaN      NaN   NaN      NaN    NaN   

  RockyMountainPower QuestarGas GrangerHunter WVCC UtahInfras Xmission  \
0                NaN        NaN           NaN  NaN        NaN      NaN   
1                NaN        NaN           NaN  NaN        NaN      NaN   

  Walgreens Winco Walmart Lucky SamsClub Maceys Davis Harmons Reams Smiths  \
0       NaN   NaN     NaN   NaN      NaN    NaN   NaN     NaN   NaN    NaN   
1       NaN   NaN     NaN   NaN      NaN    NaN   NaN     NaN   NaN    NaN   

  Albertons FreshMarket  NPS EarthGrains Chevron Shell CostcoGas Maverik  \
0       NaN         NaN  NaN         NaN     NaN   NaN       NaN     NaN   
1       NaN         NaN  NaN         NaN     NaN   NaN       NaN     NaN   

  7-Eleven HarmonsGas FastStop CapitalOne-B CapitalOne-C Progressive USBank  \
0      NaN        NaN      NaN          NaN          NaN         NaN    NaN   
1      NaN        NaN      NaN          NaN          NaN         NaN    NaN   

  DFCU ThdLoanSvcs KholsTelechk Count Categories  
0  NaN         NaN          NaN   NaN        NaN  
1  NaN         NaN          NaN   NaN        NaN